# Generated by Django 2.2 on 2019-09-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(help_text='Created')),
                ('requests', models.TextField(default='{"version": 1, "raw": []}', help_text='Requests by user, JSON-encoded')),
                ('response', models.TextField(help_text='Current response (text)', null=True)),
                ('_audio_response', models.TextField(help_text='FS path to current response (audio)', null=True)),
            ],
        ),
    ]
