# Generated by Django 2.2 on 2019-09-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ydc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialogue',
            name='requests',
        ),
        migrations.AddField(
            model_name='dialogue',
            name='meta',
            field=models.TextField(default='', help_text='Arbitrary JSON-encoded metadata for this dialogue'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='request',
            field=models.TextField(help_text='Current question (text)', null=True),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='_audio_response',
            field=models.TextField(help_text='FS path to current response (path to audio)', null=True),
        ),
    ]
