# Generated by Django 2.2 on 2019-09-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ydc', '0002_auto_20190928_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='rabbit_updated',
            field=models.BooleanField(default=False),
        ),
    ]
